const fs = require("fs");
const lines = [];
lines.push('import { NextRequest, NextResponse } from "next/server"');
lines.push('');
lines.push('export async function POST(req: NextRequest) {');
lines.push('  try {');
lines.push('    const { baseUrl, key } = await req.json()');
lines.push('    if (!key) return NextResponse.json({ error: "API key is required" }, { status: 400 })');
lines.push('');
lines.push('    const url = (baseUrl || "https://api.api2d.com/v1").replace(/\\/$/, "") + "/chat/completions"');
lines.push('    const res = await fetch(url, {');
lines.push('      method: "POST",');
lines.push('      headers: {');
lines.push('        Authorization: "Bearer " + key,');
lines.push('        "Content-Type": "application/json",');
lines.push('      },');
lines.push('      body: JSON.stringify({');
lines.push('        model: "deepseek-chat",');
lines.push('        messages: [{ role: "user", content: "say ok" }],');
lines.push('        max_tokens: 5,');
lines.push('      }),');
lines.push('      signal: AbortSignal.timeout(10000),');
lines.push('    })');
lines.push('');
lines.push('    if (!res.ok) {');
lines.push('      const text = await res.text().catch(() => "")');
lines.push('      return NextResponse.json({ error: "API returned " + res.status + ": " + text.slice(0, 300) }, { status: 400 })');
lines.push('    }');
lines.push('');
lines.push('    const data = await res.json()');
lines.push('    const msg = data?.choices?.[0]?.message?.content || "(no content)"');
lines.push('    const model = data?.model || "unknown"');
lines.push('    return NextResponse.json({ message: "OK! Model: " + model + ", says: " + msg })');
lines.push('  } catch (e) {');
lines.push('    return NextResponse.json({ error: e.message || "Connection failed" }, { status: 400 })');
lines.push('  }');
lines.push('}');
lines.push('');
fs.writeFileSync("src/app/api/relay-test/route.ts", lines.join("\n"), "utf8");
console.log("done");
